#!/bin/bash
# Скрипт для компиляции и запуска Modern Lineage II Player Characters System Client

GAME_CPP_FILE="player_characters_system_game.cpp"
EXECUTABLE_NAME="ModernLineage2_PlayerCharactersSystem"

echo "👥 Компиляция Modern Lineage II Player Characters System Client..."
echo "🎯 Особенности системы игровых персонажей:"
echo "   ✅ 5 рас из L2 деобфусцированного клиента (Human, Elf, Dwarf, Orc, DarkElf)"
echo "   ✅ 5 классов персонажей с уникальным оружием"
echo "   ✅ Детализированные модели персонажей с анимацией"
echo "   ✅ Полоски здоровья и маны для всех персонажей"
echo "   ✅ Реалистичный ИИ персонажей с действиями"
echo "   ✅ Система имен персонажей по расам"
echo "   ✅ Анимация движения, атаки и заклинаний"
echo "   ✅ Система уровней и опыта персонажей"

echo "🔨 Компилируем систему игровых персонажей..."
g++ "$GAME_CPP_FILE" -o "$EXECUTABLE_NAME" -lGL -lGLU -lglut -lm

if [ $? -eq 0 ]; then
    echo "✅ Компиляция успешна! Запускаю систему игровых персонажей..."
    nohup "./$EXECUTABLE_NAME" > /tmp/player_characters_system_game.log 2>&1 &
    GAME_PID=$!
    echo "$GAME_PID" > /tmp/player_characters_system_game.pid
    echo "🚀 Запуск Modern Lineage II Player Characters System Client..."
    echo ""
    echo "👥 ===== MODERN LINEAGE II PLAYER CHARACTERS SYSTEM ЗАПУЩЕН! ====="
    echo ""
    echo "🎮 PID: $GAME_PID"
    echo "📝 Логи: /tmp/player_characters_system_game.log"
    echo ""
    echo "👥 СИСТЕМА ИГРОВЫХ ПЕРСОНАЖЕЙ:"
    echo "   👤 25 персонажей разных рас и классов"
    echo "   🏹 5 классов: Warrior, Mage, Archer, Priest, Rogue"
    echo "   🌍 5 рас: Human, Elf, Dwarf, Orc, DarkElf"
    echo "   ⚔️  Уникальное оружие для каждого класса"
    echo "   💚 Полоски здоровья и маны"
    echo "   🎭 Реалистичные имена персонажей по расам"
    echo "   🤖 ИИ с действиями: движение, атака, заклинания"
    echo "   📊 Система уровней и опыта"
    echo ""
    echo "🎮 УПРАВЛЕНИЕ:"
    echo "   WASD     - Движение игрока"
    echo "   Стрелки  - Поворот камеры"
    echo "   T        - Переключить цикл день/ночь"
    echo "   R        - Переключить дождь и ветер"
    echo "   ЛКМ      - Взаимодействие"
    echo "   ESC      - Выход"
    echo ""
    echo "👥 РАСЫ ПЕРСОНАЖЕЙ:"
    echo "   👤 Human - Люди (Aragorn, Gandalf, Legolas, Gimli, Frodo)"
    echo "   🧝 Elf - Эльфы (Elrond, Galadriel, Thranduil, Celeborn, Arwen)"
    echo "   🧙 Dwarf - Дворфы (Thorin, Balin, Dwalin, Fili, Kili)"
    echo "   👹 Orc - Орки (Azog, Bolg, Lurtz, Gothmog, Grishnakh)"
    echo "   🧛 DarkElf - Темные эльфы (Drizzt, Jarlaxle, Artemis, Entreri, Catti-brie)"
    echo ""
    echo "⚔️  КЛАССЫ ПЕРСОНАЖЕЙ:"
    echo "   ⚔️  Warrior - Воин (меч)"
    echo "   🧙 Mage - Маг (посох)"
    echo "   🏹 Archer - Лучник (лук)"
    echo "   ⛪ Priest - Жрец (священный символ)"
    echo "   🗡️  Rogue - Разбойник (кинжал)"
    echo ""
    echo "🎭 АНИМАЦИИ ПЕРСОНАЖЕЙ:"
    echo "   🚶 Движение - покачивание вверх-вниз"
    echo "   ⚔️  Атака - быстрое покачивание с оружием"
    echo "   🔮 Заклинание - медленное покачивание"
    echo "   💚 Полоски здоровья и маны над головой"
    echo "   🎨 Цвета персонажей по расам"
    echo ""
    echo "🤖 ИИ ПЕРСОНАЖЕЙ:"
    echo "   🚶 Случайное движение каждые 3 секунды"
    echo "   ⚔️  Случайные атаки (10% вероятность)"
    echo "   🔮 Случайные заклинания (5% вероятность)"
    echo "   🎯 Поиск пути к случайным целям"
    echo "   📊 Обновление каждые 3 секунды"
    echo ""
    echo "🛑 Для остановки: kill $GAME_PID или pkill -f $EXECUTABLE_NAME"
    echo "📊 Мониторинг: tail -f /tmp/player_characters_system_game.log"
    echo ""
    echo "✅ Система игровых персонажей успешно запущена и работает!"
    echo "👥 Наблюдайте за живыми персонажами с реалистичным ИИ!"
    echo "🎯 Попробуйте нажать R для включения дождя и посмотрите на анимации!"
else
    echo "❌ Ошибка компиляции!"
    exit 1
fi

